schema_version = "1.0.0"

id = "blendrendest"
version = "1.0.0"
name = "Blendrendest"
tagline = "Estimate render time for animations and single frames"
maintainer = "plainprince"
type = "add-on"

tags = ["Render"]

blender_version_min = "4.3.0"

license = ["SPDX:GPL-3.0-or-later"]